### ISSUE TITLE
 Only the first “expect” failure for a testcase is logged in the report

### ISSUE THREAD

**Issue by mjsan** [allure-framework/mocha-allure-reporter#15] opened 2016-04-20 09:13 UTC
I'm using protractor with mocha-allure reporter. In a test, when multiple "expect" statements are there,only the first "expect" statement result gets logged in the report.Please find sample code below

```
var chai = require('chai');
var chaiAsPromised = require('chai-as-promised');
chai.use(chaiAsPromised);
var expect = chai.expect;

describe('Allure report for multiple expect', function() {

 it('Check Allure', function(done) {
    expect("first checkpoint").to.equal("is displayed")
    expect("second checkpoint").to.equal("is not displayed")
    expect("third checkpoint").to.equal("is not displayed")
});      

})     
```
The allure report displays only first failure Allure Report 

![screenshot](https://cloud.githubusercontent.com/assets/18571086/14669395/48891c18-0706-11e6-961c-c16ed6f4fe18.png)

I need all the failures for all the expect statements in the testcase. Is there any way i can achieve this?

Thanks!!

**Comment by just-boris** [comment] 2016-04-20 10:19
It is not the Allure issue. Do you have more "assertion failed" messages with different reporters?

As for me, it seems that Mocha by design breaks only first failed assertion and doesn't continue the test.

**Comment by mjsan** [comment] 2016-04-20 11:52
Seems to be so...I tried with spec.... 

![spec](https://cloud.githubusercontent.com/assets/18571086/14673578/5c8bcb14-071c-11e6-97d7-aa3d4170c46f.png)

Is there any way i can achieve this ?

Previous to this, i was using jasmine with screenshot reporter ...In it multiple failures were logged in the report

**Comment by just-boris** [comment] 2016-04-20 11:57
> Previous to this, I was using jasmine with screenshot reporter ...In it multiple failures were logged in the report

That's is the difference in Jasmine and Mocha behavior. If you want to behavior like Jasmine has, you should use Jasmine.

Closing that as not actually an issue.

**Closed by just-boris** 2016-04-20 11:57 UTC
